{
 "title": "m3trics_intent",
 "time": { "from": "2021-12-31T23:00:00.000Z", "to": "2022-01-25T22:59:58.000Z" },
 "templating": {
  "list": [
   {
    "name": "period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "channel",
    "query": "SELECT channel_name FROM conversation_channels"
   },
   { "name": "top", "query": "10" },
   {
    "name": "intent",
    "query": "SELECT user_intent\n  FROM conversation_events \nGROUP BY user_intent \nORDER BY COUNT (event_serial_id) DESC\nLIMIT $top"
   }
  ]
 },
 "panels": [
  { "title": "$period(ly) Intent Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$period(ly) Intent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  creation_timestamp AS \"Timestamp\",\n  user_intent as \"intent\",\n  COUNT(user_intent) AS \"num\"\nFROM conversation_events\nGROUP BY 1,2\nORDER BY 1,3\nLIMIT $top"
    }
   ]
  },
  {
   "title": "$period(ly) Intent - Detail",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  conversation_events.creation_timestamp as \"Timestamp\",\n  channel_name AS \"channel\"\nFROM conversation_channels, conversation_events\nWHERE\n  conversation_channels.channel_id = conversation_events.channel_id\nLIMIT $top"
    }
   ]
  },
  {
   "title": "$period(ly) Intent #",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(creation_timestamp, '1d') AS time,\r\n  COUNT(user_intent),\r\n  user_intent as metric\r\nFROM conversation_events\r\nWHERE user_intent IS NOT NULL\r\nGROUP BY 1,3\r\nORDER BY 1 ASC, 2 DESC"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(creation_timestamp, '1d') AS time,\n  COUNT(user_intent),\n  user_intent as metric\nFROM conversation_events\nWHERE user_intent IS NOT NULL AND $__timeFilter(creation_timestamp)\nGROUP BY 1,3\nORDER BY 1 ASC, 2 DESC\n"
    }
   ]
  }
 ]
}