{
 "title": "m3trics_KPI",
 "tags": [ "menu" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "precision",
    "label": "period",
    "query": "halfhour,day,week,month,quarter"
   },
   {
    "name": "channel",
    "query": "select  key from m3_dm.filter where filter.name = 'channel'"
   },
   {
    "name": "m3_ep",
    "query": "select  key from m3_dm.filter where filter.name = 'm3_ep'"
   },
   {
    "name": "authenticated",
    "query": "select  key from m3_dm.filter where filter.name = 'authenticated'"
   },
   {
    "name": "segment",
    "query": "select  key from m3_dm.filter where filter.name = 'segment'"
   }
  ]
 },
 "panels": [
  {
   "title": "${precision}(ly) KPIs - Total (Inbound + Outbound)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  sum(anonymous_customers) AS \"anonymous_customers\",\n  sum(customers) AS \"customers\",\n  sum(new_customers) AS \"new_customers\",\n  sum(new_customers)::numeric / nullif(sum(customers)::numeric, 0) * 100.0 AS \"% new_customers\",\n  sum(sessions) AS \"sessions\",\n  sum(inbound_silent + outbound_silent) AS \"ghost\",\n  sum(inbound_silent + outbound_silent)::numeric / nullif(sum(sessions)::numeric, 0) *100.0 AS \"% ghost\",\n  sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha + outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha) AS \"managed\",\n  sum(inbound_no_mode+outbound_no_mode) AS \"no_mode\",\n  sum(inbound_no_mode+outbound_no_mode)::numeric / nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha + outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric, 0)*100.0 AS \"% no_mode\",\n  sum(inbound_va+outbound_va) AS \"va\",\n  sum(inbound_va+outbound_va)::numeric / nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha + outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric, 0)*100.0 AS \"% va\",\n  sum(inbound_hybrid + outbound_hybrid) AS \"hybrid\",\n  sum(inbound_hybrid + outbound_hybrid)::numeric / nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha + outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric, 0)*100.0 AS \"% hybrid\",\n  sum(inbound_ha + outbound_ha) AS \"ha\",\n  sum(inbound_ha + outbound_ha)::numeric / nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha + outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric, 0)*100.0 AS \"% ha\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' AND\n  channel IN ($channel) AND\n  m3_ep IN ($m3_ep) AND\n  authenticated IN ($authenticated) AND\n  segment IN ($segment)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${precision}(ly) KPI (Inbound + outbound) - Detailed",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  tstamp AS time,\n  channel, m3_ep, authenticated, segment,anonymous_customers, customers,\n\tnew_customers, \n  (new_customers)::numeric / nullif((customers)::numeric, 0) * 100.0 AS \"% new_customers\",\n\tsessions,\n\tinbound_silent + outbound_silent as ghost,\n  (inbound_silent + outbound_silent)::numeric / nullif((sessions)::numeric, 0) *100.0 AS \"% ghost\",\n\tsessions - inbound_silent - outbound_silent  as managed,\n\tinbound_no_mode + outbound_no_mode as no_mode, \n\tinbound_va + outbound_va as va_mode,\n\tinbound_hybrid + outbound_hybrid as hybrid_mode, \n\tinbound_ha + outbound_ha as ha_mode \n\t--,in_msg, nu_msg, understood_msg, disamb_msg ,\n\t--disamb_dyn_msg , data_collect_msg, to_ha_msg, unclassified_msg\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ([[channel]]) AND\n  m3_ep IN ([[m3_ep]]) AND\n  authenticated IN ([[authenticated]]) AND\n  segment IN ([[segment]])\n\nORDER BY 1 desc\n\n\n"
    }
   ]
  },
  {
   "title": "${precision}(ly) KPIs - Inbound managed - Abs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  sum(inbound_no_mode) AS \"no_mode\",\n  sum(inbound_va) AS \"va_mode\",\n  sum(inbound_hybrid) AS \"hybrid_mode\",\n  sum(inbound_ha) AS \"ha_mode\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ([[channel]]) AND\n  m3_ep IN ([[m3_ep]]) AND\n  authenticated IN ([[authenticated]]) AND\n  segment IN ([[segment]])\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${precision}(ly) KPIs - Inbound managed - %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  sum(inbound_no_mode)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0) AS \"no_mode\",\n  sum(inbound_va)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0) AS \"va_mode\",\n  sum(inbound_hybrid)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0) AS \"hybrid_mode\",\n  sum(inbound_ha)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0) AS \"ha_mode\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ([[channel]]) AND\n  m3_ep IN ([[m3_ep]]) AND\n  authenticated IN ([[authenticated]]) AND\n  segment IN ([[segment]])\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${precision}(ly) KPIs - Inbound managed",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha) AS \"managed\",\n  sum(inbound_no_mode) AS \"no_mode\",\n  sum(inbound_no_mode)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0)*100.0 AS \"% no_mode\",\n  sum(inbound_va) AS \"va_mode\",\n  sum(inbound_va)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0)*100.0 AS \"% va_mode\",\n  sum(inbound_hybrid) AS \"hybrid_mode\",\n  sum(inbound_hybrid)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0)*100.0 AS \"% hybrid_mode\",\n  sum(inbound_ha) AS \"ha_mode\",\n  sum(inbound_ha)::numeric/nullif(sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha)::numeric,0)*100.0 AS \"% ha_mode\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ([[channel]]) AND\n  m3_ep IN ([[m3_ep]]) AND\n  authenticated IN ([[authenticated]]) AND\n  segment IN ([[segment]])\nGROUP BY 1\nORDER BY 1 desc"
    }
   ]
  },
  {
   "title": "${precision}(ly) KPIs - Outbound managed",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  sum(outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha) AS \"managed\",\n  sum(outbound_no_mode) AS \"no_mode\",\n  sum(outbound_no_mode)::numeric/nullif(sum(outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric,0)*100.0 AS \"% no_mode\",\n  sum(outbound_va) AS \"va_mode\",\n  sum(outbound_va)::numeric/nullif(sum(outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric,0)*100.0 AS \"% va_mode\",\n  sum(outbound_hybrid) AS \"hybrid_mode\",\n  sum(outbound_hybrid)::numeric/nullif(sum(outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric,0)*100.0 AS \"% hybrid_mode\",\n  sum(outbound_ha) AS \"ha_mode\",\n  sum(outbound_ha)::numeric/nullif(sum(outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha)::numeric,0)*100.0 AS \"% ha_mode\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ([[channel]]) AND\n  m3_ep IN ([[m3_ep]]) AND\n  authenticated IN ([[authenticated]]) AND\n  segment IN ([[segment]])\nGROUP BY 1\nORDER BY 1 desc"
    }
   ]
  },
  {
   "title": "${precision}(ly) sessions (Inbound + outbound) by service",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  channel||':'||m3_ep AS metric,\n  sum(sessions) AS \"sessions\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ($channel) AND\n  m3_ep IN ($m3_ep) AND\n  segment IN ($segment)\nGROUP BY 1,2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "${precision}(ly) managed (Inbound + outbound) sessions by service",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  channel||':'||m3_ep AS metric,\n  sum(sessions - inbound_silent - outbound_silent) AS \"managed\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ($channel) AND\n  m3_ep IN ($m3_ep) AND\n  authenticated IN ($authenticated) AND\n  segment IN ($segment)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "${precision}(ly) sessions (Inbound + outbound) by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  channel||':'||m3_ep AS metric,\n  sum(sessions) AS \"sessions\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ([[channel]]) AND\n  m3_ep IN ([[m3_ep]]) AND\n  authenticated IN ([[authenticated]]) AND\n  segment IN ([[segment]])\n\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "${precision}(ly) managed sessions (Inbound + outbound) by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  channel||':'||m3_ep AS metric,\n  sum(sessions - inbound_silent - outbound_silent) AS \"managed\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ([[channel]]) AND\n  m3_ep IN ([[m3_ep]]) AND\n  authenticated IN ([[authenticated]]) AND\n  segment IN ([[segment]])\n\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "${precision}(ly) KPIs - Inbound",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  sum(sessions - outbound_silent - outbound_no_mode - outbound_va - outbound_hybrid - outbound_ha) AS \"sessions\",\n  sum(inbound_silent) AS \"ghost\",\n  sum(inbound_no_mode + inbound_va + inbound_hybrid + inbound_ha) AS \"managed\",\n  sum(inbound_no_mode) AS \"no_mode\",\n  sum(inbound_va) AS \"va\",\n  sum(inbound_hybrid) AS \"hybrid\",\n  sum(inbound_ha) AS \"ha\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ($channel) AND\n  m3_ep IN ($m3_ep) AND\n  authenticated IN ($authenticated) AND\n  segment IN ($segment)\nGROUP BY 1\nORDER BY 1 desc"
    }
   ]
  },
  {
   "title": "${precision}(ly) KPIs - Outbound",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(tstamp,$__interval),\n  sum(sessions - inbound_silent - inbound_no_mode - inbound_va - inbound_hybrid - inbound_ha) AS \"sessions\",\n  sum(outbound_silent) AS \"ghost\",\n  sum(outbound_no_mode + outbound_va + outbound_hybrid + outbound_ha) AS \"managed\",\n  sum(outbound_no_mode) AS \"no_mode\",\n  sum(outbound_va) AS \"va\",\n  sum(outbound_hybrid) AS \"hybrid\",\n  sum(outbound_ha) AS \"ha\"\nFROM m3_dm.kpi\nWHERE\n  $__timeFilter(tstamp) AND\n  precision = '${precision}' and\n  channel IN ($channel) AND\n  m3_ep IN ($m3_ep) AND\n  authenticated IN ($authenticated) AND\n  segment IN ($segment)\nGROUP BY 1\nORDER BY 1 desc"
    }
   ]
  }
 ]
}